language: node_js
node_js:
  - "11.0"
  - "10.0"
  - "9.0"
  - "8.0"
  - "6.0"
install:
  - npm install
  - npm run-script build
script:
  - npm test
jobs:
  include:
    - stage: coverage
      node_js: "10.0"
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js