language: node_js
node_js:
  - '16.0'
  - '14.0'
  - '12.0'
  - '10.0'
install:
  - npm install
  - npm run-script build
script:
  - npm test
jobs:
  include:
    - stage: coverage
      node_js: '10.0'
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
